In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("DateFruit_Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [7]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [8]:
df.shape

(898, 35)

In [9]:
X = df.drop(columns = "Class")
y = df["Class"]

In [10]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [11]:
y.head()

0    BERHI
1    BERHI
2    BERHI
3    BERHI
4    BERHI
Name: Class, dtype: str

In [12]:
df["Class"].unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [13]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [15]:
scaler = StandardScaler()

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

# ANN

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

In [33]:
X_train_tensor = torch.tensor(X_train_scale, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scale, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [34]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [35]:
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=32)

In [36]:
# Build our ANN model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            # 1st hidden layer
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),

            # 2nd hidden layer
            nn.Linear(64, 64),
            nn.ReLU(),

            # o/p layer
            nn.Linear(64, 7),
        )
    def forward(self, x):
        return self.model(x)

In [37]:
model = ANN()

# loss and optimizer

crietrion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [38]:
# Train ANN

epochs = 100
for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb, yb in train_dataloader:
        optimizer.zero_grad()
    
        outputs = model(xb)
        loss = crietrion(outputs, yb)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    train_loss = running_loss / len(train_dataloader)
    print(f"epoch: {epoch+1} / {epochs}, loss = {train_loss}")

epoch: 1 / 100, loss = 1.7131025272866953
epoch: 2 / 100, loss = 1.1462779407915862
epoch: 3 / 100, loss = 0.757636528948079
epoch: 4 / 100, loss = 0.5767377226249032
epoch: 5 / 100, loss = 0.45948485835738806
epoch: 6 / 100, loss = 0.39866261702516803
epoch: 7 / 100, loss = 0.3599093627670537
epoch: 8 / 100, loss = 0.3229103575096182
epoch: 9 / 100, loss = 0.2959539728320163
epoch: 10 / 100, loss = 0.28232300411099975
epoch: 11 / 100, loss = 0.25730652264926746
epoch: 12 / 100, loss = 0.24349616079226785
epoch: 13 / 100, loss = 0.23799286588378574
epoch: 14 / 100, loss = 0.21574150673721149
epoch: 15 / 100, loss = 0.2151710977372916
epoch: 16 / 100, loss = 0.19782289020393207
epoch: 17 / 100, loss = 0.19321411750886752
epoch: 18 / 100, loss = 0.18119381287175676
epoch: 19 / 100, loss = 0.1786417369933232
epoch: 20 / 100, loss = 0.17116891301196555
epoch: 21 / 100, loss = 0.15893497447604718
epoch: 22 / 100, loss = 0.16007400368866714
epoch: 23 / 100, loss = 0.15124958518730558
epoch: 24 / 100, loss = 0.14446822974992835
epoch: 25 / 100, loss = 0.14456880303180736
epoch: 26 / 100, loss = 0.13781670205619023
epoch: 27 / 100, loss = 0.13464084883099017
epoch: 28 / 100, loss = 0.13226789867748384
epoch: 29 / 100, loss = 0.1307458106590354
epoch: 30 / 100, loss = 0.12519108010051044
epoch: 31 / 100, loss = 0.11640281230211258
epoch: 32 / 100, loss = 0.1137441822692104
epoch: 33 / 100, loss = 0.10920982151899648
epoch: 34 / 100, loss = 0.11229398929635467
epoch: 35 / 100, loss = 0.11005081058196399
epoch: 36 / 100, loss = 0.10870542263855106
epoch: 37 / 100, loss = 0.10111463102309601
epoch: 38 / 100, loss = 0.09642959450897963
epoch: 39 / 100, loss = 0.097654371805813
epoch: 40 / 100, loss = 0.09339070603575396
epoch: 41 / 100, loss = 0.08789880055448283
epoch: 42 / 100, loss = 0.0873356199134951
epoch: 43 / 100, loss = 0.0851557419999786
epoch: 44 / 100, loss = 0.08205113454681376
epoch: 45 / 100, loss = 0.08124640640681205
epoch: 46 / 100, loss = 0.08104055488239163
epoch: 47 / 100, loss = 0.08069016776331094
epoch: 48 / 100, loss = 0.07926265620019125
epoch: 49 / 100, loss = 0.07650750357171764
epoch: 50 / 100, loss = 0.0735538651275894
epoch: 51 / 100, loss = 0.0713359734610371
epoch: 52 / 100, loss = 0.06913492407487787
epoch: 53 / 100, loss = 0.0649288676922088
epoch: 54 / 100, loss = 0.06711438395406889
epoch: 55 / 100, loss = 0.06414975776620534
epoch: 56 / 100, loss = 0.0636596001441712
epoch: 57 / 100, loss = 0.0612362012591051
epoch: 58 / 100, loss = 0.05746240002791519
epoch: 59 / 100, loss = 0.05858005996307601
epoch: 60 / 100, loss = 0.05716042127460241
epoch: 61 / 100, loss = 0.05460269012204979
epoch: 62 / 100, loss = 0.05373929659633533
epoch: 63 / 100, loss = 0.05337421855200892
epoch: 64 / 100, loss = 0.056995272555429
epoch: 65 / 100, loss = 0.05773469263120838
epoch: 66 / 100, loss = 0.050438604722528355
epoch: 67 / 100, loss = 0.048620119366956795
epoch: 68 / 100, loss = 0.05066012461548266
epoch: 69 / 100, loss = 0.042397854323296444
epoch: 70 / 100, loss = 0.043390553920408304
epoch: 71 / 100, loss = 0.04191325829647805
epoch: 72 / 100, loss = 0.03903215200356815
epoch: 73 / 100, loss = 0.04474391298287589
epoch: 74 / 100, loss = 0.03942528391337913
epoch: 75 / 100, loss = 0.05186331724626538
epoch: 76 / 100, loss = 0.03726956068092714
epoch: 77 / 100, loss = 0.03507250671922837
epoch: 78 / 100, loss = 0.03535767620348412
epoch: 79 / 100, loss = 0.032470756622901914
epoch: 80 / 100, loss = 0.0296411763512246
epoch: 81 / 100, loss = 0.0322264079409449
epoch: 82 / 100, loss = 0.02911968336886038
epoch: 83 / 100, loss = 0.03222824677663005
epoch: 84 / 100, loss = 0.028518630799068058
epoch: 85 / 100, loss = 0.02776248945409189
epoch: 86 / 100, loss = 0.030199581514234127
epoch: 87 / 100, loss = 0.0285393295445196
epoch: 88 / 100, loss = 0.036743713644049734
epoch: 89 / 100, loss = 0.035378708058725235
epoch: 90 / 100, loss = 0.025183476426679154
epoch: 91 / 100, loss = 0.024474777301530474
epoch: 92 / 100, loss = 0.022867570914652035
epoch: 93 / 100, loss = 0.022882334351458627
epoch: 94 / 100, loss = 0.022730634557893096
epoch: 95 / 100, loss = 0.0226178129972971
epoch: 96 / 100, loss = 0.019942318231029356
epoch: 97 / 100, loss = 0.019643344764557223
epoch: 98 / 100, loss = 0.02259497941755082
epoch: 99 / 100, loss = 0.017820989004457773
epoch: 100 / 100, loss = 0.01955598357902921

In [41]:
# Evaluate

model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_dataloader:
        outputs = model(xb)
        _, predicted = torch.max(outputs, 1) # ex for tensor=[2,5,3,7,3,2,5], this max returns 2 values (max_value, idx_of_that_value) and idx is the predicted value, max_value is not of any use so _ means we dont want to store this value 

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # we can directly do y_test.shape to check this but it is a alternate way of finding the actual samples in each batch

print("Accuracy:", correct / total)

Accuracy: 0.9333333333333333